#!/usr/bin/env python3
# build_fixtures_f2c1c2.py -- hand-built synthetic NIF fixtures for
# PE_GAMEBRYO_ORACLE_F2_C1_C2_ACCEPTANCE_GUARDS_R1_20261004
# (Desktop post-audit
#  C:\Users\User\Documents\ChatGPT\PE\
#  PE_GAMEBRYO_ORACLE_F2_DESKTOP_POST_AUDIT_20261003\REPORT.md, findings
#  F2-C1/P2 (a nonzero user-defined version can end SOURCE=ACCEPTED +
#  TOOL=PASS although the pinned source rejects) and F2-C2/P2 (an
#  out-of-range LoadTopLevelObjects root ID does not participate in
#  link-integrity and can end INTEGRITY=PASS + TOOL=PASS)).
#
# QC DISCIPLINE: every byte below is derived INDEPENDENTLY from the pinned
# source canon (NiStream.cpp
# E955C36EBBB442029E00BE8A154726741B8454A607F2DC043F1FD542B009DC25:
#   L46-50    ms_uiNifMinUserDefinedVersion =
#             ms_uiNifMaxUserDefinedVersion = GetVersion(0,0,0,0) = 0,
#             NULL_LINKID = 0xffffffff;
#   L111-112  constructor: m_uiNifFileVersion = 0,
#             m_uiNifFileUserDefinedVersion = 0;
#   L303-360  LoadHeader: line; 'File Format' test; NIF version + gates;
#             user-defined version read IFF ver >= GetVersion(10,0,1,8)
#             (L334-338) + min/max gates (L340-345 OLDER_VERSION,
#             L347-352 LATER_VERSION, both return false BEFORE the
#             uiObjects read L355-357);
#   L362-385  LoadTopLevelObjects: per uiLinkID: NULL_LINKID -> NULL,
#             else DEBUG-only assert(uiLinkID < GetSize()) + UNCHECKED
#             GetAt (NiTArray.inl L135-139 m_pBase[uiIndex]);
#   L506-509  LoadStream: !LoadHeader() -> return false (the unambiguous
#             propagated rejection for the user-version gate);
# LoadRTTI L412-449, LoadObjectGroups L470-487, per-class loaders as in
# the F2 generator) -- NOT from the adapter code under correction.
#
# All bytes are OUR OWN synthetic data. Zero proprietary content.
#
# REPO POLICY (P3 hygiene, ordered by the human): the repo-wide .gitignore
# excludes *.nif (zero NIF files are tracked anywhere in this repo by
# design). The generated fixtures are kept OUTSIDE the published package
# root in this run's EXTERNAL sandbox (default output directory below);
# this committed script is the deterministic regeneration source
# (byte-identical output; SIZE + SHA256 pins in ../INPUT_IDENTITIES.md).
# Nothing generated by this script is committed.
#
# Usage:
#   python build_fixtures_f2c1c2.py [outdir]   (default: the run's external
#                                              sandbox -- see DEFAULT_OUTDIR)
#
# Fixture family (all declare NIF 10.1.0.0, HEADER_NUM_BLOCKS=1, RTTI table
# [NiNode], one fully adapter-supported NiNode body, zero children/effects,
# object groups 0, footer top-level count 1 -- byte-identical construction
# to the F2 positive control fx_VALID_positive.nif, 167B/48B24BB5...):
#   fx_VALID_user_version_0_root_0.nif -- THE VALID POSITIVE CONTROL for
#     BOTH guards: USER_DEFINED_VERSION=0.0.0.0 (inside the pinned gate
#     [0.0.0.0, 0.0.0.0]) and top-level root ID 0 (in range for
#     num_blocks=1). Byte-identical to the F1/F2 battery fixture A /
#     fx_VALID_positive.nif (the discriminator-pair BASE for everything
#     below). Must remain SOURCE=ACCEPTED, ADAPTER_DECODE_COVERAGE=COMPLETE,
#     ADAPTER_INTEGRITY=PASS, TOOL_VERDICT=PASS, accepted=true, inspect
#     exit 0 in BOTH ordinary and --full-decode (no over-fail-closed).
#   fx_C1_INVALID_user_version_1.nif -- C1 counterexample: differs from the
#     base in ONLY the user-defined-version DWORD (0.0.0.0 -> 0.0.0.1).
#     Pinned source: LoadHeader reads it (10.1.0.0 >= 10.0.1.8) and the
#     gate [0.0.0.0,0.0.0.0] rejects (LATER_VERSION, L347-352) ->
#     LoadHeader false -> LoadStream L508-509 false -> Load() false.
#     Expected post-fix (BOTH modes): SOURCE_PREDICTED=REJECTED,
#     TOOL_VERDICT=FAIL, accepted=false, inspect exit != 0; coverage
#     NOT_MEASURED (the rejection precedes the uiObjects read; no object
#     bytes are decoded just to obtain counts).
#   fx_C2_INVALID_root_9999.nif -- C2 counterexample: differs from the base
#     in ONLY the footer/root DWORD (0 -> 9999; 9999 >= num_blocks=1 is out
#     of range, not the NULL sentinel). Expected post-fix (BOTH modes):
#     scene_graph.roots keeps the raw representation [9999];
#     TOP_LEVEL_ROOT_LINK_INTEGRITY=FAIL -> LINK_INTEGRITY=FAIL ->
#     ADAPTER_INTEGRITY=FAIL -> TOOL_VERDICT=FAIL, accepted=false, exit != 0;
#     SOURCE=UNRESOLVED (pinned source: DEBUG-only assert + unchecked GetAt
#     + LoadTopLevelObjects is void -> no unambiguous propagated false);
#     coverage stays COMPLETE (the body decode is unaffected).
#   fx_C2_INVALID_root_FFFFFFFE.nif -- C2 sentinel-bypass probe: differs
#     from the base in ONLY the footer/root DWORD (0 -> 0xFFFFFFFE; the
#     parser's raw representation may display it as signed -2). Must NOT
#     bypass the range check via signedness: the guard validates the
#     NORMALIZED u32 (0xFFFFFFFE != NULL_LINKID and >= num_blocks -> FAIL).
#   fx_C2_NULL_root_FFFFFFFF.nif -- C2 NULL-sentinel probe: differs from
#     the base in ONLY the footer/root DWORD (0 -> 0xFFFFFFFF; the raw
#     representation may display as signed -1). This IS the source
#     NULL_LINKID (NiStream.cpp L50, L374-377): the ORIGINAL maps it to a
#     NULL top object -- it must NOT produce an out-of-range-root failure
#     (verified by fixture EXECUTION, not source reading alone). Permitting
#     NULL does NOT independently prove SOURCE=ACCEPTED or TOOL=PASS.

import hashlib
import os
import struct
import sys

DEFAULT_OUTDIR = (r"C:\Users\User\AppData\Local\Temp\opencode"
                  r"\PE_GAMEBRYO_ORACLE_F2_C1_C2_20261004\sandbox\01_FIXTURES")

VER_10_1_0_0 = 0x0A010000
USER_GATE = 0x0A000108        # GetVersion(10, 0, 1, 8)
NULL_LINK = 0xFFFFFFFF

# pinned historical pin (F2 package INPUT_IDENTITIES.md): the byte-identical
# base must reproduce EXACTLY; the generator fails loudly on any deviation.
BASE_SIZE = 167
BASE_SHA256 = ("48B24BB5100F424ABB266A8D10BB1F6C57A854C1960B53A46C27"
               "FEB901436984")


def rtti_string(s):
    # NiStream::LoadRTTIString L1142-1153: u32 length + bytes.
    b = s.encode("latin-1")
    return struct.pack("<I", len(b)) + b


def cstring(s):
    # NiStream::LoadCString: i32 length; bytes if > 0.
    b = s.encode("latin-1")
    return struct.pack("<i", len(b)) + b


def header(n_blocks, user_ver=0):
    # LoadHeader L303-360: line; u32 version; u32 user version iff
    # file >= 10.0.1.8 (10.1.0.0 qualifies); u32 uiObjects.
    return (b"Gamebryo File Format, Version 10.1.0.0\n"
            + struct.pack("<I", VER_10_1_0_0)
            + struct.pack("<I", user_ver)
            + struct.pack("<I", n_blocks))


def ninode_body(name="root", gid=0, children=(), effects=()):
    # Hand-derived from the pinned per-class loaders for 10.1.0.0.
    out = struct.pack("<I", gid)            # NiObject GroupID (gate range)
    out += cstring(name)                     # NiObjectNET name
    out += struct.pack("<I", 0)              # extraData multi-link count
    out += struct.pack("<I", NULL_LINK)      # controller link
    out += struct.pack("<H", 0)              # NiAVObject flags u16
    out += struct.pack("<3f", 0.0, 0.0, 0.0)             # translate
    out += struct.pack("<9f", 1.0, 0.0, 0.0,             # rotate identity
                       0.0, 1.0, 0.0,
                       0.0, 0.0, 1.0)
    out += struct.pack("<f", 1.0)                       # scale
    out += struct.pack("<I", 0)              # properties list (v >= 5.0.0.19)
    out += struct.pack("<I", NULL_LINK)      # collision link
    out += struct.pack("<I", len(children))  # NiNode children list
    out += b"".join(struct.pack("<I", c) for c in children)
    out += struct.pack("<I", len(effects))   # NiNode effects list
    out += b"".join(struct.pack("<I", e) for e in effects)
    return out


def footer(roots):
    # LoadTopLevelObjects L362-385: u32 count + one link-ID DWORD per root.
    # The link ID is a SOURCE unsigned int (NiStreamLoadBinary u32); the
    # adapter's historical raw representation is signed i32 -- both encodings
    # of 0..0xFFFFFFFF are the same 4 bytes; the C2 guard normalizes.
    return struct.pack("<I", len(roots)) + \
        b"".join(struct.pack("<I", r) for r in roots)


def build_valid(user_ver=0, root=0):
    """The valid NiNode positive control with parameterized user-version
    and footer-root DWORDs (everything else byte-identical)."""
    return (header(1, user_ver=user_ver)
            + struct.pack("<H", 1)
            + rtti_string("NiNode")
            + struct.pack("<H", 0)              # object type index -> NiNode
            + struct.pack("<I", 0)              # object groups
            + ninode_body("root")
            + footer([root]))


def write(outdir, name, data):
    path = os.path.join(outdir, name)
    with open(path, "wb") as fh:
        fh.write(data)
    print("%s size=%d sha256=%s" %
           (name, len(data), hashlib.sha256(data).hexdigest().upper()))
    return path


def assert_single_dword_diff(base, mutant, label):
    """Non-circular discriminator verification: the mutant must be the
    same size and differ from the base in EXACTLY one contiguous 4-byte
    window (the mutated DWORD -- the file layout is not DWORD-aligned, so
    the window is positional, not alignment-derived)."""
    assert len(base) == len(mutant), \
        "%s: size drift %d vs %d" % (label, len(base), len(mutant))
    diffs = [i for i in range(len(base)) if base[i] != mutant[i]]
    assert diffs, "%s: mutant is byte-identical to the base" % label
    assert max(diffs) - min(diffs) <= 3, \
        "%s: more than one DWORD differs: %r" % (label, diffs)
    return min(diffs)


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUTDIR
    if not os.path.isdir(outdir):
        os.makedirs(outdir)

    # BASE: the valid positive control (user version 0, root 0). Must be
    # byte-identical to the pinned F2 positive control.
    base = build_valid()
    base_sha = hashlib.sha256(base).hexdigest().upper()
    assert len(base) == BASE_SIZE and base_sha == BASE_SHA256, (
        "base fixture drift: size=%d sha256=%s (pinned %d / %s)"
        % (len(base), base_sha, BASE_SIZE, BASE_SHA256))
    write(outdir, "fx_VALID_user_version_0_root_0.nif", base)

    # C1: ONLY the user-defined-version DWORD changes (offset 43 in the
    # header layout: line 39B + ver 4B -> [43:47]).
    c1 = build_valid(user_ver=1)
    off = assert_single_dword_diff(base, c1, "C1_user_version")
    assert off == 43 and c1[43:47] == struct.pack("<I", 1), \
        "C1: the mutated DWORD is not the user-defined version at 43"
    write(outdir, "fx_C1_INVALID_user_version_1.nif", c1)

    # C2: ONLY the footer/root DWORD changes (the last 4 bytes of the file).
    for name, root, expect_u32 in (
            ("fx_C2_INVALID_root_9999.nif", 9999, 9999),
            ("fx_C2_INVALID_root_FFFFFFFE.nif", 0xFFFFFFFE, 0xFFFFFFFE),
            ("fx_C2_NULL_root_FFFFFFFF.nif", 0xFFFFFFFF, 0xFFFFFFFF)):
        m = build_valid(root=root)
        off = assert_single_dword_diff(base, m, name)
        assert off == len(base) - 4 and \
            struct.unpack("<I", m[off:off + 4])[0] == expect_u32, \
            "%s: the mutated DWORD is not the footer root" % name
        write(outdir, name, m)

    # raw-vs-normalized representation note for the two sentinel-class
    # roots (recorded for QC; the adapter's raw i32 representation):
    for name, root in (("fx_C2_INVALID_root_FFFFFFFE.nif", 0xFFFFFFFE),
                       ("fx_C2_NULL_root_FFFFFFFF.nif", 0xFFFFFFFF)):
        raw_i32 = struct.unpack("<i", struct.pack("<I", root))[0]
        print("%s root_u32=0x%08X raw_i32=%d normalized_u32=%d "
              "is_null_sentinel=%s"
              % (name, root, raw_i32, root & 0xFFFFFFFF,
                 (root & 0xFFFFFFFF) == NULL_LINK))


if __name__ == "__main__":
    main()
