#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
S13 AMEND R1 DOCUMENTATION PATCH (v3) -
PE_935_STATIC_LANDMARK_4057_CALLSITE_TRACE_R1_20261003

Bounded R1 repair-round documentation patch (F-P2-1 texts, F-P3-1, F-P3-2,
F-P3-4 and the three QC confirmation notes). Every replacement is verified to
occur exactly once BEFORE any write (fail-closed: on any mismatch the script
exits non-zero and writes NOTHING).

Matching is two-tier per replacement:
  tier 1 (exact): literal old string, CRLF/LF-tolerant line endings, with
                  dash/arrow/section-sign positions matched as single-character
                  wildcards (en/em/figure-dash, horizontal-bar, arrow and
                  section variants all match);
  tier 2 (flex):  additionally whitespace-run tolerant (space runs may differ).
The applied replacement preserves the matched region's line-ending style.

NO measured value is changed by this script: all measured statuses/values stay
exactly as measured; only descriptive text, counters and additive notes are
aligned with the committed raw evidence.
Interpreter: python 3.12.10. Invoke: python 03_SCRIPTS/s13_amend_r1_doc_patch.py
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.normpath(os.path.join(HERE, ".."))
RAW = os.path.join(PKG, "01_RAW")

DASH = "\u2014"
ARROW = "\u2192"
SECT = "\u00a7"

PATCHES = [
    # ---- F-P3-2: NEW_PCG_FUNCTIONS_DETAILED 19 -> 18 everywhere stated
    ("00_CONTROL/RUN_BUDGET.md",
     "NEW_PCG_FUNCTIONS_DETAILED=19/60",
     "NEW_PCG_FUNCTIONS_DETAILED=18/60",
     "F-P3-2"),
    ("02_ANALYSIS/NOT_CHECKED.md",
     "NEW_PCG_FUNCTIONS_DETAILED = 19 (FUN_00599d30; g2: 008dfcd0, 008f0780, 008e7b80,",
     "NEW_PCG_FUNCTIONS_DETAILED = 18 (FUN_00599d30; g2: 008dfcd0, 008f0780, 008e7b80,",
     "F-P3-2"),
    ("02_ANALYSIS/NEGATIVE_CONTROLS.md",
     "EXECUTED: reach-check over all 19 measured functions against the fixed canon",
     "EXECUTED: reach-check over all 18 measured functions against the fixed canon",
     "F-P3-2"),
    ("02_ANALYSIS/NEGATIVE_CONTROLS.md",
     "measured 19-function path (integer ids, pointers, strings only " + DASH,
     "measured 18-function path (integer ids, pointers, strings only " + DASH,
     "F-P3-2"),
    ("02_ANALYSIS/TRANSFORM_PROVENANCE.md",
     "known transform target field appears anywhere in the 19 measured functions\n(01_RAW/G1..G6 listings).",
     "known transform target field appears anywhere in the 18 measured functions\n(01_RAW/G1..G6 listings).",
     "F-P3-2"),
    ("05_REPORT/DRAFT_FINAL_REPORT.md",
     "NIE. The mandatory falsifier FIRED. Reach-check over all 19 measured functions",
     "NIE. The mandatory falsifier FIRED. Reach-check over all 18 measured functions",
     "F-P3-2"),
    ("05_REPORT/DRAFT_FINAL_REPORT.md",
     "Nie " + DASH + " no spatial semantics and no float triples exist anywhere on the 19\nmeasured functions (integer ids, pointers, strings only). E10 discipline",
     "Nie " + DASH + " no spatial semantics and no float triples exist anywhere on the 18\nmeasured functions (integer ids, pointers, strings only). E10 discipline",
     "F-P3-2"),
    ("05_REPORT/DRAFT_FINAL_REPORT.md",
     "NEW_PCG_FUNCTIONS_DETAILED       60      19  (FUN_00599d30 + g2 x5 + g3 x5 +\n                                            g4 x2 + g5 x4 + g6 x1 + H-series counted\n                                            at their rounds; see NOT_CHECKED.md)",
     "NEW_PCG_FUNCTIONS_DETAILED       60      18  (FUN_00599d30 + g2 x5 + g3 x5 +\n                                            g4 x2 + g5 x4 + g6 x1; see\n                                            NOT_CHECKED.md)",
     "F-P3-2"),

    # ---- F-P2-1: reach-check artifact texts corrected (the JSON itself is
    #      regenerated by s12; these are the analysis-side descriptions)
    ("02_ANALYSIS/RETRACTIONS_SUPERSESSIONS.md",
     "## R-2 " + DASH + " s7 reach-check superseded by s8 (same file, wider coverage)\n\n```text\nSUPERSEDED (current meaning): the FALSIFIER_REACH_CHECK.json first written by\ns7_curate_g4.py covered g1..g4 only. s8_curate_g5.py regenerated the same file\n(schema-compatible) over g1..g5. The g6 function (FUN_00821e70) was measured\nafterwards; its zero-hit row is recorded in TEMPLATE_ROLE_TEST.md " + SECT + "4 and its\nmeasured set lives in 01_RAW/G6_SIDS_PARSER.json. The final interpreted\nconclusion (TOTAL direct template-machinery hits on the 4057 path = 0 for the\nregistry identity; 1 x generic FUN_004D1430 inside FUN_00823C10, classified as\na shared container primitive, not a template consumer) is unchanged by every\nversion.\n```",
     "## R-2 " + DASH + " FALSIFIER_REACH_CHECK.json artifact history corrected (R1 amend; finding F-P2-1)\n\n```text\nCORRECTED (R1 amend, finding F-P2-1): the FALSIFIER_REACH_CHECK.json shipped\nwith the original package was the s7_curate_g4.py version (stage S7; 13\nfunctions = g1..g4 + the containing function; TOTAL_DIRECT_TEMPLATE_MACHINERY_\nHITS = 0 over that subset only) " + DASH + " the s8_curate_g5.py g1..g5 regeneration\ndescribed by the original R-2 never landed in the package, and the g6 function\nwas never in the artifact at all. R1 regeneration: 03_SCRIPTS/s12_falsifier_\nreach_check_v2.py rebuilt the artifact (schema-compatible) from the curated\ng1..g6 raw JSONs over ALL 18 measured functions: total_functions_checked = 18;\nTOTAL_DIRECT_TEMPLATE_MACHINERY_HITS = 1 (the shared GENERIC mapfind\nFUN_004D1430 called at 0x00823C57 inside FUN_00823C10 on the string-table\nmanager map @[mgr+4], singleton DAT_00BA12F4) classified NOT a template-registry\nedge (different singleton than the registry tree DAT_00BA1824, referenced only\ninside getter FUN_0043A550; composite key; string values; FUN_0072F580 not on\nthe path); TOTAL_TEMPLATE_REGISTRY_EDGES = 0. QC independently measured the\nsame single hit over all 18 windows (04_QC/TARGETED_QC_REPORT.md Q8). The\ninterpreted conclusion (0 template-registry edges on the 4057 path) is\nunchanged by every version of the artifact.\n```",
     "F-P2-1"),
    ("02_ANALYSIS/TEMPLATE_ROLE_TEST.md",
     "## 4. REACH-CHECK ARTIFACT (01_RAW/FALSIFIER_REACH_CHECK.json, g1..g5)\n\nAll 19 functions measured this run (full listings + callee sets) tested for\ndirect calls to the fixed canon machinery VA set",
     "## 4. REACH-CHECK ARTIFACT (01_RAW/FALSIFIER_REACH_CHECK.json, regenerated over g1..g6 " + DASH + " R1 amend)\n\nAll 18 functions measured this run (full listings + callee sets) tested for\ndirect calls to the fixed canon machinery VA set",
     "F-P2-1"),
    ("02_ANALYSIS/TEMPLATE_ROLE_TEST.md",
     "G6_FUN_00821e70                       : 0 hits (added in this analysis; measured\n                                          set extends the s8 artifact by this row)\n```",
     "G6_FUN_00821e70                       : 0 hits (row regenerated into the\n                                          artifact by the R1 script " + DASH + " the\n                                          original artifact shipped without\n                                          G5/G6 rows; see RETRACTIONS R-2)\n\nTOTAL: 18 functions checked; 1 generic-machinery hit; 0 template-registry\nedges (row-consistent with the regenerated artifact; QC independently\nmeasured the same single hit over 18 windows " + DASH + " 04_QC Q8).\n```",
     "F-P2-1"),

    # ---- F-P3-1: STEP-8 PUSH ECX address relabeled to the physical 0x00821C2C
    ("02_ANALYSIS/CALLSITE_DATAFLOW.md",
     "        0x00821C27  51 / 0x00821C2B 50  PUSH ECX / PUSH EAX ; 4057 = arg2; &local = arg3",
     "        0x00821C2C  51 / 0x00821C2B 50  PUSH ECX / PUSH EAX ; 4057 = arg2; &local = arg3",
     "F-P3-1"),

    # ---- F-P3-4a: byte-identical call shapes -> same callee/argument shape,
    #      differing this-pointer slots (verified from the g1 listing before write)
    ("02_ANALYSIS/TEMPLATE_ROLE_TEST.md",
     "The code treats all six series members as the same value class (same PUSH->same\ncallee pattern, byte-identical call shapes " + DASH + " s4 windows). Four of the six are",
     "The code treats all six series members as the same value class (same PUSH ->\nsame callee FUN_008DFCD0, same arg1 class " + DASH + " but NOT byte-identical call\nshapes: 0xFD4..0xFD8 pass this = LEA ECX,[ESP+0x2C] while the 0xFD9 anchor\npasses this = LEA ECX,[ESP+0xC8] " + DASH + " same callee/argument shape, different\nthis-pointer slots; s4 windows). Four of the six are",
     "F-P3-4a"),

    # ---- F-P3-4b: 62 unique PUSH imm32 -> precise immediate census wording
    ("02_ANALYSIS/NEGATIVE_CONTROLS.md",
     "62 unique PUSH imm32 values " + DASH + " small integers (0..0x16), UI ids (0xFF, 0x1DF,",
     "62 unique PUSH immediate values (NOT an imm32-only census: the decoded\nPUSH-immediate set includes imm8/0x6A-form pushes such as the small integers\n0..0x16 and 0x3C; QC's independent imm32-only/0x68-form byte census found 49\nunique imm32 values " + DASH + " 04_QC/TARGETED_QC_REPORT.md F-P3-4b) " + DASH + " small integers\n(0..0x16), UI ids (0xFF, 0x1DF,",
     "F-P3-4b"),

    # ---- QC confirmation note 1: RTTI chain-walk facts (executor + QC agreement;
    #      behavioral identity NOT upgraded)
    ("02_ANALYSIS/CALLSITE_DATAFLOW.md",
     "and on match calls FUN_00599d30() " + ARROW + " the anchored function is invoked inside the\nRTTI-gated ArkRepairUI initialization path. (Ghidra-RTTI-labeled; independent\nvtable-4 chain walk NOT performed this run " + DASH + " see NOT_CHECKED.)",
     "and on match calls FUN_00599d30() " + ARROW + " the anchored function is invoked inside the\nRTTI-gated ArkRepairUI initialization path. (Ghidra-RTTI-labeled; independent\nvtable-4 chain walk NOT performed this run " + DASH + " see NOT_CHECKED. R1 AMEND NOTE:\nQC's independent RTTI chain walks now CONFIRM the chain-walk facts " + DASH + " gate Type\nDescriptor 0x00B7DDE8 = '.PAVArkRepairUI_Impl@@', unwind vtable 0x00A80704 ->\nCOL 0x00AA276C -> TD 0x00B7DED8 = '.?AVArkRepairUI@@', store vtable 0x00A7A948\n-> COL 0x00A9EDD4 -> TD 0x00B6E084 = '.?AVComponent@ArkUI@@' (04_QC/\nTARGETED_QC_REPORT.md Q6). Executor + QC agree on the chain-walk facts; class\nBEHAVIORAL identity remains exactly as before, NOT upgraded.)",
     "QC-note-1"),
    ("02_ANALYSIS/OBJECT_IDENTITY_TRACE.md",
     "      (\"add component with text\" style store). The class LABEL is\n      Ghidra-RTTI-derived (STRONGLY_SUPPORTED); an independent vtable-4 ->\n      COL -> TD chain walk was NOT performed this run (NOT_CHECKED).",
     "      (\"add component with text\" style store). The class LABEL is\n      Ghidra-RTTI-derived (STRONGLY_SUPPORTED); an independent vtable-4 ->\n      COL -> TD chain walk was NOT performed this run (NOT_CHECKED). R1 AMEND\n      NOTE: QC's independent chain walk CONFIRMS the chain-walk fact " + DASH + " vtable\n      0x00A7A948 -> COL 0x00A9EDD4 -> TD 0x00B6E084 = '.?AVComponent@ArkUI@@'\n      (04_QC/TARGETED_QC_REPORT.md Q6). Executor + QC agree on the chain-walk\n      fact; class BEHAVIORAL identity remains exactly as before (not upgraded\n      to behavioral semantics).",
     "QC-note-1"),
    ("02_ANALYSIS/OBJECT_IDENTITY_TRACE.md",
     "  => FUN_00599D30 executes inside the RTTI-gated ArkRepairUI initialization.\n```",
     "  => FUN_00599D30 executes inside the RTTI-gated ArkRepairUI initialization.\n```\n\nR1 AMEND NOTE: QC's independent RTTI chain walks (04_QC/TARGETED_QC_REPORT.md\nQ6) CONFIRM the caller-side chain-walk facts: gate Type Descriptor 0x00B7DDE8\n= '.PAVArkRepairUI_Impl@@' (pointer-form TypeDescriptor of ArkRepairUI_Impl);\nunwind-store vtable 0x00A80704 -> COL 0x00AA276C -> TD 0x00B7DED8 =\n'.?AVArkRepairUI@@'. Executor + QC agree on the chain-walk facts; class\nBEHAVIORAL identity remains exactly as before (labels stay RTTI-symbol\nreadings; not upgraded to behavioral semantics).",
     "QC-note-1"),
    ("02_ANALYSIS/NOT_CHECKED.md",
     "N-07  RTTI chain walks (vtable-4 -> COL -> TD) for 0x00A7A948\n      (ArkUI::Component), ArkRepairUI vtable / ArkRepairUI_Impl Type\n      Descriptor: the labels are Ghidra RTTI-analyzer readings of the binary's\n      own RTTI symbols (STRONGLY_SUPPORTED); no independent byte-walk was run.",
     "N-07  RTTI chain walks (vtable-4 -> COL -> TD) for 0x00A7A948\n      (ArkUI::Component), ArkRepairUI vtable / ArkRepairUI_Impl Type\n      Descriptor: the labels are Ghidra RTTI-analyzer readings of the binary's\n      own RTTI symbols (STRONGLY_SUPPORTED); no independent byte-walk was run.\n      R1 AMEND NOTE: QC's independent chain walks (04_QC/TARGETED_QC_REPORT.md\n      Q6) now CONFIRM all three chain-walk facts (store vtable 0x00A7A948 =\n      '.?AVComponent@ArkUI@@'; unwind vtable 0x00A80704 = '.?AVArkRepairUI@@';\n      gate TD = '.PAVArkRepairUI_Impl@@' pointer-form). Executor + QC agree on\n      the chain-walk facts; class BEHAVIORAL identity remains exactly as before\n      (not upgraded to behavioral semantics). This N-07 row remains an honest\n      record of the EXECUTOR's own run scope.",
     "QC-note-1"),
    ("05_REPORT/DRAFT_FINAL_REPORT.md",
     "independent RTTI chain walks (labels are Ghidra RTTI readings);",
     "independent RTTI chain walks by the executor (labels are Ghidra RTTI readings;\nR1 note: QC's independent walks CONFIRM the chain-walk facts " + DASH + " 04_QC Q6;\nbehavioral identity not upgraded);",
     "QC-note-1"),
    ("05_REPORT/DRAFT_FINAL_REPORT.md",
     "NOT_CHECKED N-07).",
     "NOT_CHECKED N-07; R1: QC's independent chain walks CONFIRM the chain-walk facts " + DASH + " 04_QC Q6; behavioral identity not upgraded).",
     "QC-note-1"),

    # ---- QC confirmation note 2: sids.vfs first-entry nuance (record only)
    ("02_ANALYSIS/RETRACTIONS_SUPERSESSIONS.md",
     "identity pin (129,040 B, D58EF1D2...) and container census remain valid.\n```",
     "identity pin (129,040 B, D58EF1D2...) and container census remain valid.\nData nuance (R1 amend, record-only; QC-confirmed " + DASH + " 04_QC/TARGETED_QC_REPORT.md):\nthe first sids payload entry is an empty string with id 2021; the payload\nstill closes exactly under the documented layout with 3,887 entries.\n```",
     "QC-note-2"),
    ("02_ANALYSIS/CALLSITE_DATAFLOW.md",
     "measured layout with **3,887 entries / 3,887 unique u32 ids** and:",
     "measured layout with **3,887 entries / 3,887 unique u32 ids** (R1 data nuance,\nQC-confirmed " + DASH + " 04_QC: the first payload entry is an empty string with id 2021;\nthe layout still closes exactly with 3,887 entries) and:",
     "QC-note-2"),
    ("05_REPORT/DRAFT_FINAL_REPORT.md",
     "u16 count + count x (string, u32 id) (FUN_00821E70); the payload closes exactly\nwith 3,887 entries and id 0xFD9 = `S_REPAIR_UI_CLEAR_TOOLTIP`",
     "u16 count + count x (string, u32 id) (FUN_00821E70); the payload closes exactly\nwith 3,887 entries and id 0xFD9 = `S_REPAIR_UI_CLEAR_TOOLTIP` (R1 data nuance,\nQC-confirmed " + DASH + " 04_QC: the first payload entry is an empty string with id 2021;\nthe layout still closes exactly with 3,887 entries)",
     "QC-note-2"),
]


def make_patterns(old):
    """Return (exact, flex) compiled patterns for an old string. Dash/arrow/
    section-sign characters in the old are matched as single-character
    wildcards; line endings are CRLF/LF tolerant; the flex tier additionally
    tolerates whitespace-run differences."""
    esc = re.escape(old)
    for ch in ("\u2014", "\u2013", "\u2192", "\u00a7"):
        esc = esc.replace(re.escape(ch), "@@W@@")
    esc = esc.replace("@@W@@", ".")
    exact = re.compile(esc.replace(re.escape("\n"), "\\r?\\n"))
    flex_body = re.sub(r"(\\ )+", r"\\s+", esc.replace(re.escape("\n"), "\\r?\\n"))
    flex = re.compile(flex_body)
    return exact, flex


def g1_series_slot_check():
    """Verify from the committed g1 listing (01_RAW/G1_FUNCTION_DUMP.json) that
    the six series sites 0xFD4..0xFD9 each push their value then set ECX from a
    stack slot: 0xFD4..0xFD8 via LEA ECX,[ESP+0x2C], the 0xFD9 anchor via
    LEA ECX,[ESP+0xC8]. Fail closed if the committed evidence disagrees."""
    with open(os.path.join(RAW, "G1_FUNCTION_DUMP.json"), "r", encoding="utf-8") as f:
        g1 = json.load(f)
    listing = g1["measured"]["function"]["listing"]
    found = {}
    for idx, i in enumerate(listing):
        t = (i.get("text") or "").strip()
        m = re.match(r"^PUSH 0xfd([4-9])$", t)
        if not m:
            continue
        val = "fd" + m.group(1)
        assert val not in found, "duplicate PUSH 0x%s site" % val
        slot = None
        for j in range(idx + 1, min(idx + 7, len(listing))):
            tt = (listing[j].get("text") or "").strip()
            mm = re.match(r"^LEA ECX,\[ESP \+ 0x([0-9a-f]+)\]$", tt)
            if mm:
                slot = mm.group(1)
                break
        assert slot is not None, "no LEA ECX,[ESP+..] found after PUSH 0x%s" % val
        found[val] = slot
    assert sorted(found) == ["fd4", "fd5", "fd6", "fd7", "fd8", "fd9"], \
        "series incomplete: %r" % sorted(found)
    for v in ["fd4", "fd5", "fd6", "fd7", "fd8"]:
        assert found[v] == "2c", "slot for 0x%s is %s, expected 2c" % (v, found[v])
    assert found["fd9"] == "c8", "slot for 0xfd9 is %s, expected c8" % found["fd9"]
    print("G1 series slot check PASS:", json.dumps(found, sort_keys=True))


def main():
    g1_series_slot_check()  # pre-verify F-P3-4a wording against committed evidence

    by_file = {}
    for (rel, old, new, finding) in PATCHES:
        by_file.setdefault(rel, []).append((old, new, finding))

    texts = {}
    plans = {}
    # phase 1: verify every old string resolves to exactly one match (fail-closed)
    for rel, pairs in by_file.items():
        path = os.path.join(PKG, rel)
        with open(path, "rb") as f:
            raw = f.read()
        bom = raw.startswith(b"\xef\xbb\xbf")
        text = raw.decode("utf-8-sig" if bom else "utf-8")
        plan = []
        for (old, new, finding) in pairs:
            exact, flex = make_patterns(old)
            n_exact = len(exact.findall(text))
            if n_exact == 1:
                plan.append((exact, new, finding, old))
                continue
            if n_exact > 1:
                raise AssertionError("FAIL [%s] %s: %d exact matches (ambiguous) of %r"
                                     % (finding, rel, n_exact, old[:70]))
            n_flex = len(flex.findall(text))
            assert n_flex == 1, ("FAIL [%s] %s: exact=0 flex=%d for %r" % (finding, rel, n_flex, old[:70]))
            plan.append((flex, new, finding, old))
        texts[rel] = (text, bom)
        plans[rel] = plan
    print("phase 1 PASS: all %d replacements resolved exactly-once" % len(PATCHES))

    # phase 2: apply
    for rel, pairs in by_file.items():
        text, bom = texts[rel]
        for (pat, new, finding, old) in plans[rel]:
            def repl(m, _new=new):
                if "\r\n" in m.group(0):
                    return _new.replace("\n", "\r\n")
                return _new
            text, n = pat.subn(repl, text, count=1)
            assert n == 1, "apply failed [%s] %s" % (finding, rel)
        data = text.encode("utf-8-sig" if bom else "utf-8")
        with open(os.path.join(PKG, rel), "wb") as f:
            f.write(data)
        print("patched: %s (%d replacements)" % (rel, len(pairs)))
    print("S13 COMPLETE: %d replacements applied" % len(PATCHES))


if __name__ == "__main__":
    main()