#!/usr/bin/env python3
# build_fixtures_f2.py -- hand-built synthetic NIF fixtures for the F2
# acceptance/coverage/link correction run
# PE_GAMEBRYO_ORACLE_F2_ACCEPTANCE_COVERAGE_LINK_R1_20261003
# (Desktop post-audit
#  C:\Users\User\Documents\ChatGPT\PE\
#  PE_GAMEBRYO_ORACLE_TOOL_DESKTOP_POST_AUDIT_20261003\REPORT.md,
#  finding F2/P1: the final success predicate promoted accepted=true when no
#  unregistered RTTI entry existed and every objects[] slot was non-null --
#  a REGISTERED_BUT_NOT_DECODED_BY_ADAPTER boundary-only placeholder is
#  non-null but is NOT a semantic decode (false success), and a LINK_FAILURE /
#  out-of-range link was only a warning and did not fail acceptance).
#
# QC DISCIPLINE: the byte layouts below are derived INDEPENDENTLY from the
# pinned source canon (NiStream.cpp E955C36EBBB442029E00BE8A154726741B8454A6
# 07F2DC043F1FD542B009DC25: LoadHeader L303-360, LoadRTTI L412-449, LoadRTTI
# String L1142-1153, LoadObjectGroups L470-487, LoadTopLevelObjects L362-385;
# NiObject.cpp B137FE42126F496A37E7627061FF968256A6DA87D912784865609E2122FE470E:
# GroupID u32 iff 5.0.0.6 <= v < 10.1.0.114; NiObjectNET.cpp
# 2ADB8F89CDB40F8C114FEAA6E4A32DD7A1CC73BCE30D745F669458EE6F354190: name
# LoadCString, extraData multi-link list iff v >= 5.0.0.11, controller link;
# NiAVObject.cpp 72E0837149B03CCDA171BDF5E68E1E1F8C2712B2F10E7957AC3EC26344CA
# 5EA7: flags u16 + local transform 3f/9f/f + properties list + collision
# link for v >= 5.0.0.19; NiNode.cpp 38C7A1DE1E166345068D296F70F34B1ADAE27C6
# 94E19EAD8FA0FBD8B62E0E016: children + effects lists) -- NOT from the adapter
# code under correction.
#
# All bytes are OUR OWN synthetic data. Zero proprietary content.
#
# REPO POLICY (P3 hygiene, ordered by the human): the repo-wide .gitignore
# excludes *.nif (zero NIF files are tracked anywhere in this repo by design).
# The generated fixtures are kept OUTSIDE the published package root in this
# run's EXTERNAL sandbox (default output directory below); this committed
# script is the deterministic regeneration source (byte-identical output;
# SIZE + SHA256 pins in ../INPUT_IDENTITIES.md). Nothing generated by this
# script is committed.
#
# Usage:
#   python build_fixtures_f2.py [outdir]     (default: the run's external
#                                            sandbox -- see DEFAULT_OUTDIR)
#
# Fixtures (all declare NIF 10.1.0.0, user-defined version 0):
#   fx_VALID_positive.nif -- POSITIVE CONTROL: 1 header block, RTTI table
#     [NiNode], one fully adapter-supported NiNode with a valid body, zero
#     children/effects, all NULL links, groups 0, valid 1-root footer.
#     Expected post-fix: ADAPTER_DECODE_COVERAGE=COMPLETE,
#     ADAPTER_INTEGRITY=PASS, TOOL_VERDICT=PASS, inspect exit 0 (guards
#     against over-fail-closed). Byte-identical to the F1 battery fixture A
#     (tests/test_gb12.py _f1_fixtures()["A"], SIZE+SHA256 pin recorded).
#   fx_REGNOTDEC_ninode_nicamera_ninode.nif -- MANDATORY COUNTEREXAMPLE A
#     (REGISTERED_BUT_NOT_DECODED false success): 3 header blocks; RTTI
#     table [NiNode, NiCamera] (BOTH registered in the GB12 factory census;
#     NiCamera has NO adapter loader); object type indices [0, 1, 0] -- the
#     unsupported block is object 1, IN THE MIDDLE (not a trailing unknown
#     run; the known F4 presolver trailing-run defect is deliberately NOT
#     exercised). object 0 and object 2 are supported NiNodes with valid
#     bodies. The NiCamera block body is SYNTHETIC OPAQUE (GroupID u32 + 12
#     0xFF filler bytes): it is NOT a valid original NiCamera payload and
#     does not need to be -- the fixture tests the ADAPTER's acceptance
#     predicate (the adapter never decodes the body; the block is recorded
#     boundary-only with status REGISTERED_BUT_NOT_DECODED_BY_ADAPTER).
#     The 0xFF filler deterministically rejects false closure candidates
#     (u32_count bound fails on 0xFFFFFFFF). Expected pre-fix defect:
#     accepted=true / inspect exit 0 despite the boundary-only block.
#     Expected post-fix: factory_registration=YES (NiCamera IS in the 198-
#     class registry census), ADAPTER_DECODE_COVERAGE=INCOMPLETE,
#     registered_but_not_decoded_blocks=1, TOOL_VERDICT != PASS,
#     inspect exit != 0, SOURCE_PREDICTED_ORIGINAL_VERDICT=UNRESOLVED (the
#     factory knows the class, but the full original
#     LoadBinary/LinkObject/PostLinkObject path for NiCamera on these bytes
#     is NOT traced in the pinned source evidence -- no new broad source RE
#     was done to reach ACCEPTED).
#   fx_INVALID_LINK_child_out_of_range.nif -- MANDATORY COUNTEREXAMPLE B
#     (invalid link false success): 1 header block, RTTI table [NiNode],
#     one fully adapter-supported NiNode with a valid body whose children
#     list is count=1, link ID 9999 (>= header_num_blocks=1 -- out of
#     range), effects count 0, structurally closed so the parser reaches
#     the link phase. Expected pre-fix defect: accepted=true / inspect
#     exit 0 with only a LINK_FAILURE warning. Expected post-fix:
#     ADAPTER_DECODE_COVERAGE=COMPLETE, LINK_INTEGRITY=FAIL,
#     ADAPTER_INTEGRITY=FAIL, TOOL_VERDICT=FAIL (never UNRESOLVED for a
#     known detected invalid link), inspect exit != 0,
#     SOURCE_PREDICTED_ORIGINAL_VERDICT=UNRESOLVED (pinned source:
#     NiStream.cpp L245-256 GetObjectFromLinkID has only a DEBUG-only
#     assert(uiLinkID < m_kObjects.GetSize()); NiTArray.inl L136-139 GetAt
#     is an UNCHECKED raw m_pBase[uiIndex] read; LinkObject is void and its
#     return is discarded at LoadStream L576; L634 returns true
#     unconditionally -- the original behavior is debug-assert vs release-UB
#     dependent, so no unambiguous propagated rejection is provable).
#   fx_C1A_truncated_name_indexlike.nif / fx_C1B_truncated_name_fake_body.nif
#     -- byte-identical regeneration of the F1-C1 pinned counterexamples
#     (SIZE+SHA256 pins 928A1447... / 719A7EB3... in
#     docs/audits/PE_GAMEBRYO_ORACLE_F1_C1_EXTENSION_HALT_R1_20261003/
#     INPUT_IDENTITIES.md) re-generated here ONLY so this run's F1-C1
#     regression re-execution uses physically regenerated pinned bytes
#     without touching the historical package.
#
# Registry assumptions (verified by the run's QC):
#   "NiNode" IS in the GB12 factory registry AND in the adapter LOADERS;
#   "NiCamera" IS in the GB12 factory registry (198-class census) but has
#   NO adapter loader (39 loaders) -- the measured F2 premise.

import hashlib
import os
import struct
import sys

DEFAULT_OUTDIR = (r"C:\Users\User\AppData\Local\Temp\opencode"
                  r"\PE_GAMEBRYO_ORACLE_F2_20261003\sandbox\01_FIXTURES")

VER_10_1_0_0 = 0x0A010000
NULL_LINK = 0xFFFFFFFF
MAX_RTTI_LEN = 256          # NiStream.cpp L68-71
DECLARED_NAME2_LEN = 127    # 0 < 127 < MAX_RTTI_LEN (source-valid range)
MISS_NAME = "NiDesktopFirstMissing"   # 21 chars, unregistered synthetic


def rtti_string(s):
    # NiStream::LoadRTTIString L1142-1153: u32 length + bytes.
    b = s.encode("latin-1")
    return struct.pack("<I", len(b)) + b


def cstring(s):
    # NiStream::LoadCString: i32 length; bytes if > 0.
    b = s.encode("latin-1")
    return struct.pack("<i", len(b)) + b


def header(n_blocks, user_ver=0):
    # LoadHeader L303-360: line; u32 version; u32 user version iff
    # file >= 10.0.1.8 (10.1.0.0 qualifies); u32 uiObjects.
    return (b"Gamebryo File Format, Version 10.1.0.0\n"
            + struct.pack("<I", VER_10_1_0_0)
            + struct.pack("<I", user_ver)
            + struct.pack("<I", n_blocks))


def ninode_body(name="root", gid=0, children=(), effects=()):
    # Hand-derived from the pinned per-class loaders for 10.1.0.0.
    out = struct.pack("<I", gid)            # NiObject GroupID (gate range)
    out += cstring(name)                     # NiObjectNET name
    out += struct.pack("<I", 0)              # extraData multi-link count
    out += struct.pack("<I", NULL_LINK)      # controller link
    out += struct.pack("<H", 0)              # NiAVObject flags u16
    out += struct.pack("<3f", 0.0, 0.0, 0.0)             # translate
    out += struct.pack("<9f", 1.0, 0.0, 0.0,             # rotate identity
                       0.0, 1.0, 0.0,
                       0.0, 0.0, 1.0)
    out += struct.pack("<f", 1.0)                       # scale
    out += struct.pack("<I", 0)              # properties list (v >= 5.0.0.19)
    out += struct.pack("<I", NULL_LINK)      # collision link
    out += struct.pack("<I", len(children))  # NiNode children list
    out += b"".join(struct.pack("<I", c) for c in children)
    out += struct.pack("<I", len(effects))   # NiNode effects list
    out += b"".join(struct.pack("<I", e) for e in effects)
    return out


def nicamera_opaque_body():
    # SYNTHETIC OPAQUE body for the registered-but-not-decoded block:
    # GroupID u32 (gate range for 10.1.0.0) + 0xFF filler. NOT a valid
    # original NiCamera payload; the 0xFF filler makes every false closure
    # candidate fail deterministically (u32_count bound rejects 0xFFFFFFFF).
    return struct.pack("<I", 0) + b"\xFF" * 12


def footer(roots):
    # LoadTopLevelObjects L362-385: u32 count + i32 per root.
    return struct.pack("<I", len(roots)) + \
        b"".join(struct.pack("<i", r) for r in roots)


def build_v1(prefix_bytes=None):
    return header(1) + prefix_bytes


def truncated_name_table(prefix_bytes):
    # LoadRTTI L412-434 layout with a THIRD entry whose declared length is
    # source-valid (127) but whose payload is `prefix_bytes` (< 127) and
    # then EOF (the F1-C1 fixture family; byte-identical regeneration).
    out = header(1)
    out += struct.pack("<H", 3)
    out += rtti_string("NiNode")
    out += rtti_string(MISS_NAME)
    out += struct.pack("<I", DECLARED_NAME2_LEN)
    out += prefix_bytes
    return out


def write(outdir, name, data):
    path = os.path.join(outdir, name)
    with open(path, "wb") as fh:
        fh.write(data)
    print("%s size=%d sha256=%s" %
           (name, len(data), hashlib.sha256(data).hexdigest().upper()))
    return path


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUTDIR
    if not os.path.isdir(outdir):
        os.makedirs(outdir)

    # POSITIVE CONTROL: minimal fully-supported NiNode, valid body, no
    # links, valid footer. Must remain TOOL_VERDICT=PASS / exit 0 post-fix.
    write(outdir, "fx_VALID_positive.nif",
          header(1)
          + struct.pack("<H", 1)
          + rtti_string("NiNode")
          + struct.pack("<H", 0)
          + struct.pack("<I", 0)              # object groups
          + ninode_body("root")
          + footer([0]))

    # COUNTEREXAMPLE A: NiNode / NiCamera(boundary-only, MIDDLE) / NiNode.
    write(outdir, "fx_REGNOTDEC_ninode_nicamera_ninode.nif",
          header(3)
          + struct.pack("<H", 2)
          + rtti_string("NiNode")
          + rtti_string("NiCamera")
          + struct.pack("<H", 0) + struct.pack("<H", 1) + struct.pack("<H", 0)
          + struct.pack("<I", 0)              # object groups
          + ninode_body("n0", gid=0)
          + nicamera_opaque_body()
          + ninode_body("n2", gid=0)
          + footer([0]))

    # COUNTEREXAMPLE B: fully supported NiNode, children=[9999] out of
    # range (n_obj=1), structurally closed so the link phase is reached.
    write(outdir, "fx_INVALID_LINK_child_out_of_range.nif",
          header(1)
          + struct.pack("<H", 1)
          + rtti_string("NiNode")
          + struct.pack("<H", 0)
          + struct.pack("<I", 0)              # object groups
          + ninode_body("root", children=(9999,))
          + footer([0]))

    # F1-C1 pinned counterexamples (byte-identical regeneration; the F2
    # run re-executes the F1-C1 regression on physically regenerated
    # pinned bytes without touching the historical package).
    write(outdir, "fx_C1A_truncated_name_indexlike.nif",
          truncated_name_table(b"\x02\x00"))
    fake = (struct.pack("<H", 0)          # object type index -> NiNode
            + struct.pack("<I", 0)         # LoadObjectGroups: numGroups 0
            + ninode_body("root")          # 90-byte NiNode body
            + footer([0]))                # TopObjects footer
    assert len(fake) == 104
    write(outdir, "fx_C1B_truncated_name_fake_body.nif",
          truncated_name_table(fake))


if __name__ == "__main__":
    main()
